apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  ENVIRONMENT: "production"
  # This matches the name of the Service we just created!
  DB_HOST: "database-service" 
  DB_USER: "admin"
  DB_PORT: "5432"