apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
data:
  haproxy.cfg: |
    global
      log stdout format raw local0
    defaults
      log global
      mode http
      timeout connect 5000ms
      timeout client 50000ms
      timeout server 50000ms
    frontend http_front
      bind *:80
      default_backend app_back
    backend app_back
      balance roundrobin
      server app-servers app-cluster-ip:80 check 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
      - name: haproxy
        image: haproxy:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: haproxy-config-volume
          mountPath: /usr/local/etc/haproxy/
      volumes:
      - name: haproxy-config-volume
        configMap:
          name: haproxy-config
---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-service
spec:
  type: NodePort 
  selector:
    app: haproxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080